volumes:
  workspace:
    name: des-workspace
services:
  spark-master:
    image: aloneguid/des:spark-3.3.2
    ports:
      - 9090:8080
      - 7077:7077
    environment:
      - SPARK_MASTER_HOST=spark-master
      - DES_WORKLOAD=spark-master
    volumes:
      - workspace:/workspace
  spark-worker-1:
    image: aloneguid/des:spark-3.3.2
    ports:
      - 9091:8081
    environment:
      - SPARK_MASTER_HOST=spark-master
      - DES_WORKLOAD=spark-worker
    volumes:
      - workspace:/workspace
  jupyterlab:
    image: aloneguid/des:spark-3.3.2
    ports:
      - 8888:8888
    environment:
      - SPARK_MASTER_HOST=spark-master
      - DES_WORKLOAD=jupyterlab
    volumes:
      - workspace:/workspace