volumes:
  workspace:
    name: des-workspace
    driver: local
    driver_opts:
      type: none
      device: /home/alg/des-workspace
      o: bind
services:
  spark-master:
    image: aloneguid:des/spark-3.5.1
    ports:
      - 9090:8080
      - 7077:7077
    environment:
      - SPARK_MASTER_HOST=spark-master
      - DES_WORKLOAD=spark-master
    volumes:
      - workspace:/opt/workspace
  spark-worker-1:
    image: aloneguid:des/spark-3.5.1
    ports:
      - 9091:8081
    environment:
      - SPARK_MASTER_HOST=spark-master
      - DES_WORKLOAD=spark-worker
    volumes:
      - workspace:/opt/workspace
  spark-history-server:
    image: aloneguid:des/spark-3.5.1
    ports:
      - 18080:18080
    environment:
      - SPARK_MASTER_HOST=spark-master
      - DES_WORKLOAD=spark-history-server
    volumes:
      - workspace:/opt/workspace
  jupyterlab:
    image: aloneguid:des/spark-3.5.1
    ports:
      - 8888:8888
    environment:
      - SPARK_MASTER_HOST=spark-master
      - DES_WORKLOAD=jupyterlab
    volumes:
      - workspace:/opt/workspace