volumes:
  data:
    name: des-data
    driver: local
    driver_opts:
      type: none
      device: /home/alg/des
      o: bind
services:
  spark-master:
    image: aloneguid/des-spark:3.5.1
    ports:
      - 9090:8080
      - 7077:7077
    environment:
      - SPARK_MASTER_HOST=spark-master
      - DES_WORKLOAD=spark-master
    volumes:
      - data:/opt/data
  spark-worker-1:
    image: aloneguid/des-spark:3.5.1
    depends_on:
      - spark-master
    ports:
      - 9091:8081
    environment:
      - SPARK_MASTER_HOST=spark-master
      - DES_WORKLOAD=spark-worker
    volumes:
      - data:/opt/data
  spark-history-server:
    image: aloneguid/des-spark:3.5.1
    ports:
      - 18080:18080
    environment:
      - SPARK_MASTER_HOST=spark-master
      - DES_WORKLOAD=spark-history-server
    volumes:
      - data:/opt/data
  spark-thrift-server:
    image: aloneguid/des-spark:3.5.1
    depends_on:
      - spark-master
      - spark-worker-1
    ports:
      - 10000:10000
    environment:
      - SPARK_MASTER_HOST=spark-master
      - DES_WORKLOAD=spark-thrift-server
    volumes:
      - data:/opt/data
#  jupyterlab:
#    image: aloneguid/des-spark:3.5.1
#    depends_on:
#      - spark-master
#      - spark-worker-1
#    ports:
#      - 8888:8888
#    environment:
#      - SPARK_MASTER_HOST=spark-master
#      - DES_WORKLOAD=jupyterlab
#    volumes:
#      - data:/opt/data