name: Build Base Image

on:
  workflow_dispatch:

jobs:

  build-base:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build . -t aloneguid/des-base
        working-directory: ./docker/base

      # Optional: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      # Optional: Push the image to Docker Hub
      - name: Push the Docker image
        run: docker push aloneguid/des-base