name: Build Dev Jumpbox Image

on:
  workflow_dispatch:

jobs:

  build-base:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build . -t aloneguid/des-jumpbox
        working-directory: ./docker/base

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Push the Docker image
        run: docker push aloneguid/des-jumpbox